project_id = "overnight-t03"

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[auth]
enabled = true
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false

[auth.sms]
enable_signup = false
